# .github/workflows/docker-publish.yml

name: Build and Push Docker Images to Docker Hub

# Controls when the workflow will run
on:
    push:
      tags:
        - 'v*.*.*' # Trigger ONLY on version tags starting with v*.*.*.
                   
                   
    workflow_dispatch: {} 

jobs:
  # Job to build and push the Backend image
  build_and_push_backend:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out your repository code

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # Needed for multi-platform builds (optional but good practice)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Sets up Docker Buildx for advanced builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Use the secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Use the secret

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend # Path to the Backend directory relative to repo root
          file: ./Backend/Dockerfile # Path to the Backend Dockerfile
          push: true # Push the image to Docker Hub
          tags: | # Tags for the image
            ${{ secrets.DOCKERHUB_USERNAME }}/noteapp-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/noteapp-backend:${{ github.sha }}
          platforms: linux/amd64 # Specify platform(s) (optional, default is runner's platform)
          cache-from: type=gha # Enable GitHub Actions cache for Docker layers
          cache-to: type=gha,mode=max # Write cache back

  # Job to build and push the Frontend image
  build_and_push_frontend:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend # Path to the Frontend directory
          file: ./Frontend/Dockerfile # Path to the Frontend Dockerfile
          push: true
          tags: | # Tags for the image
            ${{ secrets.DOCKERHUB_USERNAME }}/noteapp-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/noteapp-frontend:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # --- IMPORTANT for Production Frontend Build ---
          # If your frontend needs build-time environment variables (like VITE_API_BASE_URL)
          # You'll need to pass them as build args here AND modify your Frontend Dockerfile
          # Example build-arg (uncomment and adjust if needed):
          build-args: |
             VITE_API_BASE_URL=${{ vars.PROD_API_BASE_URL || 'http://your-prod-backend-url/api' }}